
name: DockerHub Image Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: main Branch Checkout
      uses: actions/checkout@v3
    
    - name: Make Resources Directory
      run: mkdir ./Resources
    - name: Download Model Resources
      run: wget -O ./Resources/resnet50-11ad3fa6.pth https://storage.googleapis.com/codeadeel-github/Autism-Classification/resnet50-11ad3fa6.pth

    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build Trainer
      run: docker build -t ${{secrets.DOCKER_USER}}/autism_classification:trainer -f Build_Trainer .
    - name: Push Trainer
      run: docker push ${{secrets.DOCKER_USER}}/autism_classification:trainer
    - name: Build Server
      run: docker build -t ${{secrets.DOCKER_USER}}/autism_classification:server -f Build_Server .
    - name: Push Server
      run: docker push ${{secrets.DOCKER_USER}}/autism_classification:server
      
